#!/bin/sh
while read file
do
	case "$1" in
	"C-c")
		#procbg "$file" 
		#setbg .local/share/tempwall.png ;;
		setbg "$file" ;;
	esac
        case "$1" in
	"C-s")
		mkdir -p liked
		cp "$file" liked/
        esac

done
